name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: '*'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: Install dependencies
        run: yarn

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test

      - name: build
        run: yarn build
